### ISSUE TITLE
Dataset access denied. point odyssey

### ISSUE THREAD

**Issue by ronly2460** [kai422/DAS3R#3]
Hi, Thank you for the great work!

I am trying to download the point_odyssey. but, The access is denied by these commands.

```
# train
gdown --id 1ivaHRZV6iwxxH4qk8IAIyrOF9jrppDIP
# test
gdown --id 1jn8l28BBNw9f9wYFmd5WOCERH48-GsgB
# sample
gdown --id 1dnl9XMImdwKX2KcZCTuVDhcy5h8qzQIO
```

**Comment by kai422** [comment]
Hi @ronly2460,  

I have updated the download URL from gdown to Hugging Face. Please pull the changes and try again.  

Best regards,  
Kai

**Comment by ronly2460** [comment]
Hi, Thank you for sharing it!. I could download it.
